# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/lirex/Desktop/Lab7_PunnavitAkkarapitakchai/CMPEN331_Lab7/CMPEN331_Lab7.cache/wt [current_project]
set_property parent.project_path C:/Users/lirex/Desktop/Lab7_PunnavitAkkarapitakchai/CMPEN331_Lab7/CMPEN331_Lab7.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/lirex/Desktop/Lab7_PunnavitAkkarapitakchai/CMPEN331_Lab7/CMPEN331_Lab7.srcs/sources_1/imports/lab 7/lab7_regfile.v}
  {C:/Users/lirex/Desktop/Lab7_PunnavitAkkarapitakchai/CMPEN331_Lab7/CMPEN331_Lab7.srcs/sources_1/imports/lab 7/lab7_pc.v}
  {C:/Users/lirex/Desktop/Lab7_PunnavitAkkarapitakchai/CMPEN331_Lab7/CMPEN331_Lab7.srcs/sources_1/imports/lab 7/lab7_mux4_pcsrc.v}
  {C:/Users/lirex/Desktop/Lab7_PunnavitAkkarapitakchai/CMPEN331_Lab7/CMPEN331_Lab7.srcs/sources_1/imports/lab 7/lab7_mux2.v}
  {C:/Users/lirex/Desktop/Lab7_PunnavitAkkarapitakchai/CMPEN331_Lab7/CMPEN331_Lab7.srcs/sources_1/imports/lab 7/lab7_MIPSALU.v}
  {C:/Users/lirex/Desktop/Lab7_PunnavitAkkarapitakchai/CMPEN331_Lab7/CMPEN331_Lab7.srcs/sources_1/imports/lab 7/lab7_insmem.v}
  {C:/Users/lirex/Desktop/Lab7_PunnavitAkkarapitakchai/CMPEN331_Lab7/CMPEN331_Lab7.srcs/sources_1/imports/lab 7/lab7_extendImmediate.v}
  {C:/Users/lirex/Desktop/Lab7_PunnavitAkkarapitakchai/CMPEN331_Lab7/CMPEN331_Lab7.srcs/sources_1/imports/lab 7/lab7_dataMemory.v}
  {C:/Users/lirex/Desktop/Lab7_PunnavitAkkarapitakchai/CMPEN331_Lab7/CMPEN331_Lab7.srcs/sources_1/imports/lab 7/lab7_adder.v}
  {C:/Users/lirex/Desktop/Lab7_PunnavitAkkarapitakchai/CMPEN331_Lab7/CMPEN331_Lab7.srcs/sources_1/imports/lab 7/lab7_controlUnit.v}
  {C:/Users/lirex/Desktop/Lab7_PunnavitAkkarapitakchai/CMPEN331_Lab7/CMPEN331_Lab7.srcs/sources_1/imports/lab 7/lab7_top.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/lirex/Desktop/Lab7_PunnavitAkkarapitakchai/CMPEN331_Lab7/ZYBO_MASTER.xdc
set_property used_in_implementation false [get_files C:/Users/lirex/Desktop/Lab7_PunnavitAkkarapitakchai/CMPEN331_Lab7/ZYBO_MASTER.xdc]


synth_design -top top -part xc7z010clg400-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
